### ISSUE TITLE
Program crashes and closes itself when it gets to pizza ya san map

### ISSUE THREAD

**Issue by atmogenic** [wootguy/Glitch-Life#20]
Hi, I've been having this issue since I got the program. For some reason the program just closes itself when it gets to the two pizza_ya_san maps, the thing is that it sometimes work but then goes to crashing again when i want to change the corruptions, i've gone through each option to singularly know what's causing the issue, but its not obvious as it sometimes work but most of the time it doesn't.

All other maps (320 maps) are completely fine no others crash, just pizza_ya_san which is typical as i enjoy playing those 2 maps.

![gsrand_yyAVFoEI4u](https://user-images.githubusercontent.com/56037304/70075463-c6d0d600-15f4-11ea-85cd-1de2d2ed120e.png)

I can only do them individually as doing all the maps together crash at pizza ya san

**Comment by wootguy** [comment]
The fact that it sometimes works probably means some random choice is causing it to crash. Setting the "random_seed" config to something should cause crashes 100% of the time in that case (once you find a bad setting combination or seed).

I'll try to get this to happen on my end, but this could also be something like a bad wad or model that I don't have. If you could reproduce this in an isolated folder with a small amount of content, and then send me the zip/7z of that folder, then I can fix this pretty quick.

**Comment by wootguy** [comment]
Good news - I almost immediately got a crash when trying to randomize my 3000+ maps. There's some memory corruption going on that's likely causing this and other crashes.

**Comment by atmogenic** [comment]
sorry to sound dumb, but what u mean reproduce? you mean do what i did in that screenshot but select the "copy everything into a folder" and then send it on here?

**Comment by atmogenic** [comment]
also idk if this other thing is a bug or something, but it seems the pizza guys can only change to default army grunts and is the same with the houndeyes when they attack the shop owners. never had them change into something else from the number of times it has been fine.

**Comment by wootguy** [comment]
> what u mean reproduce?

I mean create a new folder outside of "Sven Co-op" and copy some models/sounds/etc. there and try to get it to crash again (see "Content Selection" in the readme). Then you can send just that folder instead of your entire "Sven Co-op" installation. Also be sure to use the "random_seed" setting so we both get the same results.

You might not have to bother with that since I've got a few crashes already, but if the fixes I'm working on don't work for you then I'll need to be able to troubleshoot with your exact setup.

> idk if this other thing is a bug or something, but it seems the pizza guys can only change to default army grunts and is the same with the houndeyes

looks like another bug, probably related to those "missing resource" errors.

**Comment by atmogenic** [comment]
ok i'm using a "random_seed" and just put a bunch of gibberish in "gkarsgfjsgkhsgs" since it said just text and now im doing the list of maps again.

ok it didn't crash when the random_seed was used.

**Comment by atmogenic** [comment]
Looks like it works fine when i do the random seed stuff

**Comment by wootguy** [comment]
There should be some seed that can cause the crash, but it could take a lot of attempts.

I'll add new issues for the other bugs you found.

**Comment by atmogenic** [comment]
ok, thanks for the support and looking into the isses :)

**Comment by atmogenic** [comment]
I've used the "monsters only" for the sounds and it seems its not just pizza_ya_san but all maps it doesn't work on, everything has changed like i set it to "super random"

**Comment by wootguy** [comment]
updated #22 with that comment.

I'm attaching a build here with some crash fixes. This might fix your problem, but it will be hard to know unless you find a random_seed that causes a crash.

[gsrand_x64.zip](https://github.com/wootguy/Glitch-Life/files/3924011/gsrand_x64.zip)

**Comment by atmogenic** [comment]
thanks i'll give it a try

**Comment by atmogenic** [comment]
doesn't seemed to have fixed it, I did a new randomizer with sound at "monsters only" and when it finished, i went on sven coop and loaded up pizza_ya_san1 which as soon as I hit the START button, it was a scientist voice along with the sounds of the grapple hook and after a random GO from a soldier grunt.

**Comment by wootguy** [comment]
The attachment is for fixing the original problem where the program crashes on that map. I haven't gotten to the sound bug yet.

**Comment by atmogenic** [comment]
Also there is another bug that maybe be caused by me or the program itself and that is the corruption mode not setting the type i put in the config file. I set the corruption mode to "constant" and the only "corruptions" I put was "scale" yet it hasn't change whatsoever when i use the randomizer (including todays with the troubleshooting) and yes I set the selection to "use config settings" when doing the randomizer.

![20191204230907_1](https://user-images.githubusercontent.com/56037304/70189386-1a255000-16eb-11ea-9b42-21e59c830dce.jpg)

here's a screenshot showing my in-game 

![notepad_O3CKhLX32k](https://user-images.githubusercontent.com/56037304/70189480-52c52980-16eb-11ea-9085-234193deed0c.png)

here's the settings I have in the config, mind you i've had this setting before doing the random_seed thing today

**Comment by atmogenic** [comment]
> The attachment is for fixing the original problem where the program crashes on that map. I haven't gotten to the sound bug yet.

oh sorry i thought since u quoted that issue, i thought it was a fix to it, my bad

**Comment by wootguy** [comment]
np I should’ve been more clear.

> I put was "scale" yet it hasn't change whatsoever

This one is just my bad instructions. In your screenshot you have scale set to 1 which means 100% (no scaling). For double size you would write 2, and for half size 0.5

**Comment by atmogenic** [comment]
ohh thank you for telling me that
