### ISSUE TITLE
Multiplayer map transfer

### ISSUE THREAD

**Issue by MisterFreeman15** [wootguy/Glitch-Life#23]
Hey I have a quick question, I started a P2P server  with my buddy, after the randomisation was complete I send him the folder with the content folder, so he didn’t have to download everything, but for some reason he still has to download the map when joining my game. He put the content in het addons folder just like you said.

**Comment by wootguy** [comment]
I guess the parent folder was put into svencoop_addon, instead of its contents. The path to the map for him should be:
`svencoop_addon/maps/mapname.bsp`
and not
`svencoop_addon/gsrand_output/maps/mapname.bsp`

**Comment by MisterFreeman15** [comment]
He did what you instructed but still getting the downloads

**Comment by wootguy** [comment]
I'd check which file is getting downloaded, and see if that file exists in your `gsrand_output` folder. If it does exist then things still aren't being copied right. If it doesn't exist in `gsrand_output` then there's a bug in gsrand, or you might have some plugins installed that have their own file downloads.

If it's a map that uses scripts you might need to install from [scmapdb](http://scmapdb.com/) first. I don't think the `gsrand_output` folder will copy the files used by map scripts.

One workaround could be to use [resguy](https://github.com/wootguy/resguy) to create a map package for the the gsrand_* maps (or whatever map prefix you used), then send that to him. Resguy command: `resguy gsrand_* -7z`.

**Comment by MisterFreeman15** [comment]
I only randomize the standard half life maps, so the scripts and custom content shouldn’t be a problem.

**Comment by wootguy** [comment]
alright you can skip the bit about scmapdb then
