### ISSUE TITLE
Excluded Sounds issues

### ISSUE THREAD

**Issue by GordonFrenchman** [wootguy/Glitch-Life#27]
Hi,

I hope my question won't sound stupid, but I wanted to know why some sounds are excluded from the randomization process. I ensured to encode them in the correct sound format and they share the same properties than other sounds that have been accepted.

Is there a specific reason and is there a way to fix it?

Thanks by advance for your answers!
<img width="660" alt="SND excluded" src="https://user-images.githubusercontent.com/117911048/201080598-985f77b0-6288-48aa-b083-49c57a1636d1.png">

**Comment by wootguy** [comment]
it could be:
1) File size is larger than `max_file_size` config setting.
1) File has uppercase letters and `skip_uppercase = 1` is in the config.
1) File is default/custom and excluded by the `Content Mode` setting.

**Comment by GordonFrenchman** [comment]
> 

Looks like it worked! Thanks a lot for you help! :)

**Comment by GordonFrenchman** [comment]
> it could be:
> 
> 1. File size is larger than `max_file_size` config setting.
> 2. File has uppercase letters and `skip_uppercase = 1` is in the config.
> 3. File is default/custom and excluded by the `Content Mode` setting.

Thanks a lot for you answer! It helped me a lot! :D
