### ISSUE TITLE
[enhancement] Add the ability to randomize any map

### ISSUE THREAD

**Issue by khang06** [wootguy/Glitch-Life#3]
I probably botched the title, but can you add the ability to mash together any map in any folder? I want to see if I can screw with Portal 2.

**Comment by wootguy** [comment]
Not sure I follow. You can put the program anywhere, but all maps have to be in a "maps" folder next to it. Is there a problem with renaming the folder or re-organizing the assets to match the HL layout?

Source games use a different map format so I don't think it would work anyway.

**Comment by khang06** [comment]
Well, I tried it with Portal 2. It had a ton of errors and then the gsrand_ maps no longer load ;-;

**Comment by wootguy** [comment]
I figured that would happen. Source games use different types of assets, and supporting them would take a ton of effort I think (I know next to nothing about Source game internals).

Maybe in the distant future I'll make a source version of this program, but someone else has already [started on that](http://vinesauce.com/vinetalk/viewtopic.php?p=7495).
