### ISSUE TITLE
Segmentation fault on Linux when sound randomisation is used

### ISSUE THREAD

**Issue by incognico** [wootguy/Glitch-Life#6]
As soon as I change 5) Sound Mode to anything other than "Do not change" I get a segfault of gsrand after starting.

```
Found 1 of 1 maps

Finding content...
Segmentation fault (core dumped)
```

It crashes almost instantly after "Finding content...".
All other corruptions work fine but sound crashes.

I've tried different versions of llvm to complile gsrand, no difference.
Somehow I have problems running it in lldb, gdb says the following:
```0x00007ffff72241da in strlen () from /lib/x86_64-linux-gnu/libc.so.6```

CC @Yoplitein

**Comment by Yoplitein** [comment]
There appears to be incorrect data in the `masterSize` array. On line 5696 in masterList.h change 2 to 1.

**Comment by Yoplitein** [comment]
I'm surprised this doesn't also segfault on Windows. I guess the CRT's strlen is more robust?

**Comment by wootguy** [comment]
I guess so. I wish it wasn't so I could trust my testing on Windows. 

Windows 8+ also seems to [initialize memory differently](http://forums.svencoop.com/showthread.php/43310-Need-help-with-text-menu?p=515218&viewfull=1#post515218), which makes it impossible to reproduce problems like this without a different OS (or compiler/runtime?).

**Comment by Yoplitein** [comment]
You might try MinGW.

**Comment by incognico** [comment]
Works now with the small change. But isn't it supposed to find my custom sounds and use them as replacement for the maps sounds? I see 

```Finding non-default content...
Sounds ------------- 0 (10 excluded)```

while I have almost 7000 sound files in sound/

**Comment by wootguy** [comment]
MinGW worked, and so did the masterSize change.

For the custom sound problem, yes, it should be finding your custom sounds. Which content folder are they in (svencoop, svencoop_addon, svencoop_downloads, svencoop_hd)?

I forgot svencoop_hd was a thing, so the program won't search there.

**Comment by incognico** [comment]
Using svencoop_addon. It only finds 10 sounds, every time. Sound scanning finishing way too quickly too. Could there be problematic files in the sound folder or am I hitting any limits or something?

**Comment by wootguy** [comment]
Nope, there aren't any hard-coded limits. Maybe the *nix code isn't looking deep enough into the sounds directory (i.e. only finding 10 sounds at the root of sounds/).

**Comment by incognico** [comment]
There are way more at the root of sound/. Well at least the segfault is fixed fow now.

**Comment by Yoplitein** [comment]
It's an issue of case sensitivity. Working on a fix.

**Comment by Yoplitein** [comment]
#7
