### ISSUE TITLE
Displacer models not randomized.

### ISSUE THREAD

**Issue by incognico** [wootguy/Glitch-Life#9]
The displacer weapon models are not randomized.

**Comment by CryoKeen** [comment]
Ohh let's see if we can get him to change that whenever he has some spare time! w00tguy is an epic coder and cool guy!

**Comment by wootguy** [comment]
Ok I fixed this but only because keen said I was a cool guy!

**Comment by incognico** [comment]
Fzk yea cigarettes and hookers
